version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - 3000:80
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - api
  api:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile.api
      args:
      - BUILD_PROGRESS=plain
    ports:
      - 8000:8000
    volumes:
      - ./fastapi-app:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: reactapp
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: markellytech@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    ports:
      - 5050:80
volumes:
  postgres-data:
